### ISSUE TITLE
Python 2

### ISSUE THREAD

**Issue by EvasiZ** [brycefrank/pyfor#34]
Is there any way to use pyfor with python2? I have to use it in a project including ArcPy which needs python2 to work.

Thank for the reply.

**Comment by brycefrank** [comment]
There is nothing stopping you from trying, however the dependency stack is rather deep, so the likelihood that something is not backward compatible is very high. 

That said, I think pyfor, along with other open source GIS packages, can be used in a workflow in tandem with ArcPy. pyfor supports file I/O for typical file types, like `.tif` and `.shp` (and of course `.las`) files. It is certainly possible to tie these elements together in a script, you could call the bits you need in Python 2 from Python 3 (or vice versa if you prefer) using something like:

https://stackoverflow.com/a/51702380/5249681

I was also under the impression that the latest ArcGIS Pro switched to Python 3 anyway?
