### ISSUE TITLE
TIN option for surfaces

### ISSUE THREAD

**Issue by jfprieur** [brycefrank/pyfor#48]
Hello again, apologies for the multiple posts.

Another option that would be very useful for us in our workflow is the possibility to use a TIN algorithm to create our surfaces, similar to this function in the lidR package (we are currently using).

https://www.rdocumentation.org/packages/lidR/versions/2.0.1/topics/p2r

Thank you!

**Comment by brycefrank** [comment]
Hello,

It is my impression that `scipy.interpolate.griddata` uses a Delaunay triangulation at least some point in the interpolation process, which is tightly related to TIN as far as I know. The documentation for `scipy.interpolate.griddata` is unclear whether or not this is used when the "nearest" argument is called. That said, your solution may be close at hand. If you find an existing method in `scipy.interpolate` I could easily add a wrapper, or you could integrate it into your existing codebase.

I do not expect to get to this particular feature in the near term if it requires implementing the algorithm from scratch. Let me know if you find anything.

- Bryce

**Comment by jfprieur** [comment]
Thank you for your quick reply. I should have dug down deeper in the scipy documentation, it does indeed seem to do Delaunay, I will investigate further. If I find anything specific that is easily implementable I will open another issue. You can close this one.
