### ISSUE TITLE
Tree Segmentation 

### ISSUE THREAD

**Issue by DavidEic** [brycefrank/pyfor#53]
Hi Bryce!

Im somewhat new to python so please pardon my lack of knowledge.
Im trying to do a crown segmentation of a park at my university as part of my master thesis. 
When I perform the watershed segmentation with:

```
segmentation = chm.watershed_seg(min_distance=4, threshold_abs=4).plot()
```

I get:
 
```
/peak.py:185: RuntimeWarning: invalid value encountered in greater
  mask &= image > max(thresholds)
```

Also I dont get any polygons on the output. Its just the CHM again. See figure..

When I run:

```
segmentation.segments[segmentation.segments["raster_val"] > 0]
```

I get:

```
'NoneType' object has no attribute 'segments'
````

To be honest, Im a bit clueless whats actually wrong here.
If you could help me it would be really appreciated.

Thanks so much in advance!
David

![Figure_1](https://user-images.githubusercontent.com/50298411/57196513-c63c6800-6f5d-11e9-92b4-5e1470a42a78.png)

**Comment by brycefrank** [comment]
A blind guess, here. When you make your CHM, interpolate NANs.

Try:

```{python}
chm = pc.chm(your_cell_size, interp_method="nearest")
```

**Comment by brycefrank** [comment]
Also, I will be extracting the watershed segmentation to a stand-alone package called `treeseg` in the coming months (very slowly, I have a lot of things going on). Keep an eye out for that.

**Comment by brycefrank** [comment]
Any thoughts, @DavidEic ? If it is solved, I will close.

**Comment by DavidEic** [comment]
Hi Bryce!

Thanks for the quick response and sorry for the late reply! Unfortunately it is still not solved..

This is the Code that Im using:

chm = pc.chm(0.25, interp_method = "cubic", pit_filter="median")
chm.plot()

#perform segmentation on CHM model - parameters should be improved and verified
crowns = chm.watershed_seg(min_distance=2, threshold_abs=2)

#Look at output with crown.segments['geometry'] or crown.segments['raster_val']

#and save to shapefile (best to store parameters in the filename so you know what you are doing and comparing)
final_crowns = crowns.segments[crowns.segments["raster_val"] > 0]
#best to filter some more, for example by area
NP_pc_crown_fname = '/home/bodo/Dropbox/CampusGolm-Lidar/NP_DEichhorn/NP_clip2_25cm_mindist2_thresh2_crowns.shp'

final_crowns.to_file(NP_pc_crown_fname)

I also tried interp_method=”nearest” but the same result..

Something goes definitely wrong with the peak local max function. I tried a different approach without pyfor and still get the same error when using peak local max..

David

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by brycefrank** [comment]
Interesting. Could you tell me the output of:

```
import numpy as np
print(np.sum(np.isnan(chm.array)))
```

**Comment by brycefrank** [comment]
Alternatively you can send me the tile if you like and I can take a bit closer look:

bfrank70@gmail.com

I can get to it tomorrow or wed.

**Comment by brycefrank** [comment]
I am not sure the issue, I was able to get a GeoDataFrame of segments with the following. Furthermore, my canopy height model does not show nans like yours does:

```
import pyfor
import numpy as np

pc = pyfor.cloud.Cloud('your_las.las')
chm = pc.chm(0.25, interp_method="nearest", pit_filter="median")

np.sum(np.isnan(chm.array))
>>> 0

chm.watershed_seg(min_distance=4, threshold_abs=4).segments

>>>
                                               geometry  raster_val
0     POLYGON ((364536.8912518311 5807589.840157471,...         0.0
1     POLYGON ((364785.1412518311 5807589.840157471,...         0.0
2     POLYGON ((364614.3912518311 5807589.840157471,...        22.0
...
```

I was not able to get it plotted, though.

A couple of ideas for you:

Try updating the packages in your environment:

```
conda update -n pyfor_env --all
```

and also update pyfor using the instructions in the README.
