### ISSUE TITLE
Point cloud colors

### ISSUE THREAD

**Issue by ignacioi96** [brycefrank/pyfor#61]
Hello pyfor builders! Thank you for the tool.

Any chance you can include RGB values when reading LAS/LAZ files?
or is there a specific reason why you eliminate them?
It should be a matter of adding **'red','green','blue'** within the list named **dims** within the method **_get_las_points**.

Thank you for the consideration!

**Comment by brycefrank** [comment]
Gladly. If you have a small sample .las file with colors you could provide (<50 kb) I will also add a unit test.

**Comment by brycefrank** [comment]
Pushed to develop:
7e4ecc1

The "updating" section in the README should guide the rest of the way. Make sure to check out the develop branch first:

```
git checkout develop
```

and then proceed with updating the environment.
