### ISSUE TITLE
missing else branch for tolerance parameter in KrausPfeifer1998

### ISSUE THREAD

**Issue by Crghilardi** [brycefrank/pyfor#77]
If a `tolerance` other than 0 is used in the `KrausPfeifer1998`, it doesn't get passed through to any of the functions and returns the same as leaving it as the default. 
I found this after reading through [this article](http://quantitativeecology.org/using-rlidar-and-fusion-to-delineate-individual-trees-through-canopy-height-model-segmentation/) where they use a tolerance of 1 in their `groundfilter.exe` call.

```python
ex = pyfor.ground_filter.KrausPfeifer1998(1).ground_points(cloud)
ex2 = pyfor.ground_filter.KrausPfeifer1998(1,tolerance=100).ground_points(cloud)

#returns same # of points regardless, would expect to be different
ex.data.points.shape #(2285739, 13)
ex2.data.points.shape #(2285739, 13)
```

**Comment by brycefrank** [comment]
Hey Casey,

Good catch. I should have time today for a quick patch.

-B

**Comment by brycefrank** [comment]
It seems that `self.tolerance` isn't even used in the filter. Must have been an oversight.

That said, for an immediate work around you can just set the sum of the `g` and `w` arguments to equal the tolerance you desire.

**Comment by brycefrank** [comment]
Casey,

I have pushed this fix to the `develop` branch:

3d402a1

Also, I added some instructions for installing directly from `develop` instead of via conda-forge (the develop branch is not supported in conda yet, so you will need to install directly from GitHub).
